name: Run FAIRSECO

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  RunFAIRSECO:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout FAIRSECO assets
        uses: actions/checkout@v4
        with:
          repository: SecureSECO/FAIRSECO
          path: FAIRSECO_Assets

      - name: Run FAIRSECO
        uses: SecureSECO/FAIRSECO@v1.0.2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload FAIRSECO result
        uses: actions/upload-artifact@v4
        with:
          name: fairseco-result
          path: .FAIRSECO/
          if-no-files-found: warn
